"""add staffing entry

Revision ID: bf1ab18f3d41
Revises: f9d6ab26716f
Create Date: 2026-03-10 22:41:45.914943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1ab18f3d41'
down_revision = 'f9d6ab26716f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffing_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_date', sa.Date(), nullable=False),
    sa.Column('manager_user_id', sa.Integer(), nullable=False),
    sa.Column('team_member_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.Enum('PROJECT', 'SICK_LEAVE', 'VACATION', 'HOLIDAY', 'BENCH', 'TRAINING', 'OTHER', name='activitytype', native_enum=False), nullable=False),
    sa.Column('hours', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('billing_manager_user_id', sa.Integer(), nullable=True),
    sa.Column('charged_fte', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['billing_manager_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['manager_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['team_member_id'], ['team_member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_date', 'manager_user_id', 'team_member_id', 'project_id', 'activity_type', name='uq_staffing_row')
    )
    with op.batch_alter_table('staffing_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staffing_entry_manager_user_id'), ['manager_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_staffing_entry_work_date'), ['work_date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffing_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staffing_entry_work_date'))
        batch_op.drop_index(batch_op.f('ix_staffing_entry_manager_user_id'))

    op.drop_table('staffing_entry')
    # ### end Alembic commands ###
