"""Initial migration

Revision ID: f9d6ab26716f
Revises: 
Create Date: 2026-03-10 20:13:58.389639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d6ab26716f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=255), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('cadence', sa.Enum('DAILY', 'WEEKLY', name='billingcadence', native_enum=False), nullable=False),
    sa.Column('fte', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_type', 'region', 'cadence', 'fte', name='uq_billing_rate_key')
    )
    op.create_table('cost_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('Analyst1', 'Analyst2', 'Associate1', 'Associate2', 'Associate3', 'ProjectLeader1', 'ProjectLeader2', 'ProjectLeader3', 'Manager1', 'Manager2', 'Manager3', 'SeniorManager1', 'SeniorManager2', 'SeniorManager3', 'Director', 'SeniorDirector', 'VP', name='teammemberlevel', native_enum=False), nullable=False),
    sa.Column('cost_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('classification_1', sa.String(length=255), nullable=True),
    sa.Column('classification_2', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('level', sa.Enum('Analyst1', 'Analyst2', 'Associate1', 'Associate2', 'Associate3', 'ProjectLeader1', 'ProjectLeader2', 'ProjectLeader3', 'Manager1', 'Manager2', 'Manager3', 'SeniorManager1', 'SeniorManager2', 'SeniorManager3', 'Director', 'SeniorDirector', 'VP', name='teammemberlevel', native_enum=False), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_member_employee_id'), ['employee_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', name='userrole', native_enum=False), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_code', sa.String(length=255), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_type', sa.String(length=255), nullable=False),
    sa.Column('stakeholder', sa.String(length=255), nullable=True),
    sa.Column('region', sa.String(length=255), nullable=False),
    sa.Column('nps_contact', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_case_code'), ['case_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_case_code'))

    op.drop_table('project')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('team_member', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_member_employee_id'))

    op.drop_table('team_member')
    op.drop_table('team')
    op.drop_table('cost_rate')
    op.drop_table('billing_rate')
    # ### end Alembic commands ###
